
[wifi]
user_boots_first_time = false

[wifi.ssid]
password = "password"
provider = "provider"

[wifi."180******88的Mate 60 Pro"]
password = ""
provider = "183.173.11.102"

[wifi.Cyberdog2]
password = ""
provider = ""

[wifi.Cyberdog]
provider = "10.0.0.107"
password = ""

[wifi.mi]
password = ""
provider = ""

