
[wifi]
user_boots_first_time = false

[wifi.mi]
provider = ""
password = ""

[wifi.Cyberdog]
provider = ""
password = ""

[wifi.Cyberdog2]
provider = ""
password = ""

[wifi."180******88的Mate 60 Pro"]
provider = "183.173.11.102"
password = ""

[wifi.ssid]
provider = "provider"
password = "password"

